export const GET_ALL_TODOS = "GET_ALL_TODOS";
export const GET_ONE_TODO = "GET_ONE_TODO";
export const UPDATE_ONE_TODO = "UPDATE_ONE_TODO";
export const DELETE_ONE_TODO = "DELETE_ONE_TODO";

export const ADD_ONE_SUB_TODO = "ADD_ONE_SUB_TODO";
export const GET_ALL_SUB_TODOS = "GET_ALL_SUB_TODOS";
export const DELETE_ONE_SUB_TODO = "DELETE_ONE_SUB_TODO";
export const CLEAR_ALL_SUB_TODO = "CLEAR_ALL_SUB_TODO";
